[counter]
entity-count   = 100
evt-count      = 10_000
snapshot-after = 100_000_000

[evt-log]
host          = "localhost"
port          = 5432
user          = "test"
password      = "test"
dbname        = "test"
sslmode       = "prefer"
poll-interval = "3s"

[snapshot-store]
host     = "localhost"
port     = 5432
user     = "test"
password = "test"
dbname   = "test"
sslmode  = "prefer"
