[counter]
entity-count   = 50
event-count    = 20_000
snapshot-after = 100_000_000

[event-log]
server-addr = "localhost:4222"
setup       = true

[snapshot-store]
server-addr = "localhost:4222"
setup       = true
