[package]
name          = "eventsourced-postgres"
description   = "Postgres implementation for eventsourced EvtLog and SnapshotStore"
version       = "0.1.0"
edition       = { workspace = true }
authors       = { workspace = true }
license       = { workspace = true }
readme        = { workspace = true }
homepage      = { workspace = true }
repository    = { workspace = true }
documentation = { workspace = true }

[dependencies]
eventsourced   = { path = "../eventsourced", default-features = false }
async-stream   = { workspace = true }
bb8-postgres   = { workspace = true }
bytes          = { workspace = true }
futures        = { workspace = true }
serde          = { workspace = true }
tokio          = { workspace = true, features = [ "time" ] }
thiserror      = { workspace = true }
tokio-postgres = { workspace = true }
tracing        = { workspace = true }
uuid           = { workspace = true }

[dev-dependencies]
anyhow             = { workspace = true }
prost              = { workspace = true }
testcontainers     = { workspace = true }
tokio              = { workspace = true, features = [ "macros", "rt-multi-thread" ] }
tracing-subscriber = { workspace = true }
