[package]
name          = "eventsourced-projection"
description   = "Projections for EventSourced."
version       = "0.6.1"
edition       = { workspace = true }
license       = { workspace = true }
readme        = "README.md"
homepage      = { workspace = true }
repository    = { workspace = true }
documentation = "https://docs.rs/eventsourced-projection/latest/eventsourced_projection/"
publish       = true

[dependencies]
eventsourced  = { path = "../eventsourced", version = "0.27.0", features = [ "serde_json" ] }
error-ext     = { workspace = true }
futures       = { workspace = true }
serde         = { workspace = true }
sqlx          = { workspace = true }
thiserror     = { workspace = true }
tokio         = { workspace = true }
tracing       = { workspace = true }
trait-variant = { workspace = true }

[dev-dependencies]
eventsourced           = { path = "../eventsourced", version = "0.27.0", features = [ "test" ] }
testcontainers         = { workspace = true }
testcontainers-modules = { workspace = true, features = [ "postgres" ] }
tokio                  = { workspace = true, features = [ "macros" ] }
